spring.application.name=GreenCareAI
spring.datasource.url=jdbc:postgresql://localhost:5432/greencare_AI
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
"java.configuration.enableAnnotationProcessing": true

openapi.api.key=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
openapi.api.model=gpt-4o
openapi.api.url=https://api.openai.com/v1/chat/completions
