spring.application.name=GreenCareAI

# ? Dùng bi?n môi tr??ng thay vì localhost
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

openapi.api.key=${OPENAI_API_KEY}
openapi.api.model=gpt-4o
openapi.api.url=https://api.openai.com/v1/chat/completions
